### ISSUE TITLE
Error 404 on some formats in some YT videos

### ISSUE THREAD

**Issue by deepak-jha-kgp** [AbelTesfaye/react-native-ytdl#34]
Usually, this library works great but on some videos, some of the extracted links do not seem to exist. Tried playing the extracted in browser/ react-native-video, got the same result.
Consider [this video](https://youtu.be/Cmw8kXwKt30) `https://youtu.be/Cmw8kXwKt30` 
One of the URLs (144p mp4) we get on the extraction of all available formats is [this](https://r2---sn-bpb5oupj-qxae.googlevideo.com/videoplayback?expire=1602159705&ei=-a9-X6ONLJOcvQSC_b34Cg&ip=137.59.242.23&id=o-AL3YwOIlfUpOyXt58PxLEXuQir7Ry_QyPQemwWiIndsO&itag=160&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278&source=yt_otf&requiressl=yes&mh=IO&mm=31%2C29&mn=sn-bpb5oupj-qxae%2Csn-qxa7snel&ms=au%2Crdu&mv=m&mvi=2&pl=24&pcm2=yes&initcwndbps=725000&vprv=1&mime=video%2Fmp4&otf=1&otfp=1&dur=0.000&lmt=1598103255541531&mt=1602138030&fvip=2&keepalive=yes&fexp=23915654&c=WEB&txp=7210222&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cpcm2%2Cvprv%2Cmime%2Cotf%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRAIgQ5ekZ_xd-gbtv0Z99wj8w11b1oMGENmZWHXJyZQ13PUCIB2SoudPeTlmzW4hWYdmMkIZzwwwH8cgdR-oqjU68kGt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgdwjJIyv6WqvxDne32M4-tGLP1NZqEA6CTNuQKVYIpUsCIB2tqa7dyqnxLhVbLOk1zAHti3_dc7cFe2Kylit5nSkL&ratebypass=yes), which is not available on internet.
Seeing this behavior mostly on 144p, 240p and 480p

**Comment by AbelTesfaye** [comment]
Hey, thanks for reporting. This issue should be fixed now.

**Comment by deepak-jha-kgp** [comment]
Thank you. This seems to work. However, I notice that instead of a simple mp4 resource location, I'm getting a Dash link even for non-live videos. Is this an intended change?

**Comment by AbelTesfaye** [comment]
Yes it is. Small size videos are available as dash-mpd files.

**Comment by deepak-jha-kgp** [comment]
Okay, do we have any additional benefit from this? Otherwise, I think plain mp4 did the job. Also, just to add MediaPlayer (react-native-video) in RN has very limited support for DASH. Would be great if we could roll back to the original formats with 404 fixed. Thanks

**Comment by AbelTesfaye** [comment]
I'm not sure what the reasoning behind it is, but YouTube chose to make
some of the small videos available via dash while others are available via
direct links.

The broken mp4 video in the previous version was not supposed to be
available in the first place. It was there because of a typo that resulted
in the dash playlist link not getting properly extracted. Reverting this is
not a good way to go.

But if you're looking for non-dash 144p videos, try looking through all the
available formats of the video, you might find something there.

**Comment by deepak-jha-kgp** [comment]
Thanks for this. I am able to play DASH video snow. The problem was that the downloaded files have no .mpd extension. So while playing video, we have to explicitly mention .mpd. If there is anything we can do about it, it would be great. Otherwise, let's close this issue. Thanks a lot for this.

**Comment by deepak-jha-kgp** [comment]
Another issue that I just noticed, we're getting the same DASH link, for all the DASH itags

**Comment by AbelTesfaye** [comment]
There's nothing that can be done to insert the .mpd extension, at least from the library side. You might want to download the playlist to file and add the .mpd extension there.

The reason you're seeing the same playlist url on multiple formats is because a single playlist contains representations for all itags. Your player should let you pick representations, else you can try to use an xml parser to strip out the representations you don't need.

**Comment by deepak-jha-kgp** [comment]
okay got it. Tried stripping out the representation, but now getting the original error. The extracted links for itags 135,133, (these are the ones I could test) still return a 404.

**Comment by AbelTesfaye** [comment]
Did you test this in a player? The baseurl can sometimes return a 404 and yet the segments work

**Comment by deepak-jha-kgp** [comment]
You're right. It works. Thanks. Closing this now.
